/**
 * Bibliothèque 3D BTP — CRM SDA Rénovation
 * 75+ éléments couvrant : Structure, Menuiseries, Cuisine, Sanitaire,
 * Séjour, Chambre, Charpente, Toiture, IPN, Sols, Cloisonnement
 */

export type FormeGeom = "box" | "cylinder" | "toit2pentes" | "ipn" | "escalier" | "toitplat";

export interface Element3DDef {
  id: string;
  nom: string;
  categorie: string;
  sousCategorie: string;
  emoji: string;
  // dimensions par défaut en mètres [longueur, hauteur, profondeur]
  dim: [number, number, number];
  couleur: string;         // hex
  roughness: number;       // 0=brillant 1=mat
  metalness: number;       // 0=non-métal 1=métal
  forme: FormeGeom;
  bim: {
    materiau: string;
    fabricant?: string;
    reference?: string;
    coutUHT?: number;
    unite?: string;
    norme?: string;
  };
}

// ---------------------------------------------------------------------------
// STRUCTURE & MAÇONNERIE
// ---------------------------------------------------------------------------

const STRUCTURE: Element3DDef[] = [
  {
    id: "mur-beton",
    nom: "Mur béton 20cm",
    categorie: "STRUCTURE",
    sousCategorie: "Maçonnerie",
    emoji: "🧱",
    dim: [3, 2.5, 0.2],
    couleur: "#9CA3AF",
    roughness: 0.9,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Béton armé", coutUHT: 85, unite: "m²", norme: "EN 206" },
  },
  {
    id: "mur-brique",
    nom: "Mur brique 22cm",
    categorie: "STRUCTURE",
    sousCategorie: "Maçonnerie",
    emoji: "🧱",
    dim: [3, 2.5, 0.22],
    couleur: "#C2745A",
    roughness: 0.95,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Brique monomur", coutUHT: 75, unite: "m²", norme: "DTU 20.1" },
  },
  {
    id: "mur-parpaing",
    nom: "Mur parpaing 20cm",
    categorie: "STRUCTURE",
    sousCategorie: "Maçonnerie",
    emoji: "🧱",
    dim: [3, 2.5, 0.2],
    couleur: "#B5B5B5",
    roughness: 0.9,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Parpaing creux", coutUHT: 55, unite: "m²", norme: "DTU 20.1" },
  },
  {
    id: "cloison-placo",
    nom: "Cloison placo 10cm",
    categorie: "STRUCTURE",
    sousCategorie: "Cloisonnement",
    emoji: "⬜",
    dim: [3, 2.5, 0.1],
    couleur: "#F1F5F9",
    roughness: 0.85,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Plaque de plâtre BA13", fabricant: "Knauf", coutUHT: 35, unite: "m²", norme: "DTU 25.41" },
  },
  {
    id: "poteau-beton",
    nom: "Poteau béton 40x40",
    categorie: "STRUCTURE",
    sousCategorie: "Poteaux",
    emoji: "🏛️",
    dim: [0.4, 3, 0.4],
    couleur: "#9CA3AF",
    roughness: 0.9,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Béton armé HA", coutUHT: 280, unite: "ml", norme: "Eurocode 2" },
  },
  {
    id: "dalle-beton",
    nom: "Dalle béton 20cm",
    categorie: "STRUCTURE",
    sousCategorie: "Planchers",
    emoji: "▬",
    dim: [5, 0.2, 5],
    couleur: "#CBD5E1",
    roughness: 0.8,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Béton armé", coutUHT: 120, unite: "m²", norme: "DTU 13.3" },
  },
];

// ---------------------------------------------------------------------------
// IPN / CHARPENTE MÉTALLIQUE
// ---------------------------------------------------------------------------

const IPN: Element3DDef[] = [
  {
    id: "ipn-hea100",
    nom: "IPE HEA 100",
    categorie: "CHARPENTE_METALLIQUE",
    sousCategorie: "Profilés IPN",
    emoji: "🔩",
    dim: [4, 0.1, 0.1],
    couleur: "#374151",
    roughness: 0.3,
    metalness: 0.9,
    forme: "ipn",
    bim: { materiau: "Acier S275", reference: "HEA 100", coutUHT: 28, unite: "ml", norme: "EN 10025" },
  },
  {
    id: "ipn-hea140",
    nom: "IPE HEA 140",
    categorie: "CHARPENTE_METALLIQUE",
    sousCategorie: "Profilés IPN",
    emoji: "🔩",
    dim: [5, 0.14, 0.14],
    couleur: "#374151",
    roughness: 0.3,
    metalness: 0.9,
    forme: "ipn",
    bim: { materiau: "Acier S275", reference: "HEA 140", coutUHT: 42, unite: "ml", norme: "EN 10025" },
  },
  {
    id: "ipn-hea160",
    nom: "IPE HEA 160",
    categorie: "CHARPENTE_METALLIQUE",
    sousCategorie: "Profilés IPN",
    emoji: "🔩",
    dim: [6, 0.16, 0.16],
    couleur: "#374151",
    roughness: 0.3,
    metalness: 0.9,
    forme: "ipn",
    bim: { materiau: "Acier S275", reference: "HEA 160", coutUHT: 58, unite: "ml", norme: "EN 10025" },
  },
  {
    id: "ipn-hea200",
    nom: "IPE HEA 200",
    categorie: "CHARPENTE_METALLIQUE",
    sousCategorie: "Profilés IPN",
    emoji: "🔩",
    dim: [7, 0.2, 0.2],
    couleur: "#374151",
    roughness: 0.3,
    metalness: 0.9,
    forme: "ipn",
    bim: { materiau: "Acier S355", reference: "HEA 200", coutUHT: 78, unite: "ml", norme: "EN 10025" },
  },
  {
    id: "ipn-hea240",
    nom: "IPE HEA 240",
    categorie: "CHARPENTE_METALLIQUE",
    sousCategorie: "Profilés IPN",
    emoji: "🔩",
    dim: [8, 0.24, 0.24],
    couleur: "#374151",
    roughness: 0.3,
    metalness: 0.9,
    forme: "ipn",
    bim: { materiau: "Acier S355", reference: "HEA 240", coutUHT: 105, unite: "ml", norme: "EN 10025" },
  },
  {
    id: "poutre-bois",
    nom: "Poutre bois 20x24cm",
    categorie: "CHARPENTE_METALLIQUE",
    sousCategorie: "Charpente bois",
    emoji: "🪵",
    dim: [5, 0.24, 0.2],
    couleur: "#92400E",
    roughness: 0.95,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Douglas massif C24", coutUHT: 45, unite: "ml", norme: "DTU 31.1" },
  },
];

// ---------------------------------------------------------------------------
// CHARPENTE & TOITURE
// ---------------------------------------------------------------------------

const CHARPENTE: Element3DDef[] = [
  {
    id: "charpente-fermette",
    nom: "Fermette charpente",
    categorie: "CHARPENTE",
    sousCategorie: "Charpente industrielle",
    emoji: "🏗️",
    dim: [6, 2, 0.1],
    couleur: "#A16207",
    roughness: 0.9,
    metalness: 0,
    forme: "toit2pentes",
    bim: { materiau: "Bois résineux C24", coutUHT: 38, unite: "ml", norme: "DTU 31.3" },
  },
  {
    id: "toit-2pentes",
    nom: "Toit à 2 pentes (30°)",
    categorie: "CHARPENTE",
    sousCategorie: "Couverture",
    emoji: "🏠",
    dim: [8, 2.5, 7],
    couleur: "#7C3AED",
    roughness: 0.85,
    metalness: 0,
    forme: "toit2pentes",
    bim: { materiau: "Tuiles béton", fabricant: "Edilians", coutUHT: 65, unite: "m²", norme: "DTU 40.21" },
  },
  {
    id: "toit-plat",
    nom: "Toiture terrasse",
    categorie: "CHARPENTE",
    sousCategorie: "Couverture",
    emoji: "⬛",
    dim: [8, 0.3, 7],
    couleur: "#1E293B",
    roughness: 0.7,
    metalness: 0.1,
    forme: "toitplat",
    bim: { materiau: "Étanchéité bicouche SBS", coutUHT: 95, unite: "m²", norme: "DTU 43.1" },
  },
  {
    id: "chevron",
    nom: "Chevron 7x15cm",
    categorie: "CHARPENTE",
    sousCategorie: "Charpente bois",
    emoji: "🪵",
    dim: [4, 0.15, 0.07],
    couleur: "#B45309",
    roughness: 0.9,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Sapin blanc C18", coutUHT: 12, unite: "ml", norme: "DTU 31.1" },
  },
  {
    id: "tuile-ardoise",
    nom: "Ardoise naturelle",
    categorie: "CHARPENTE",
    sousCategorie: "Couverture",
    emoji: "🏚️",
    dim: [5, 0.02, 4],
    couleur: "#475569",
    roughness: 0.75,
    metalness: 0.05,
    forme: "box",
    bim: { materiau: "Ardoise naturelle", fabricant: "Cupa Stone", coutUHT: 120, unite: "m²", norme: "DTU 40.11" },
  },
];

// ---------------------------------------------------------------------------
// MENUISERIES
// ---------------------------------------------------------------------------

const MENUISERIES: Element3DDef[] = [
  {
    id: "porte-simple",
    nom: "Porte simple 90cm",
    categorie: "MENUISERIES",
    sousCategorie: "Portes intérieures",
    emoji: "🚪",
    dim: [0.9, 2.1, 0.08],
    couleur: "#DEB887",
    roughness: 0.6,
    metalness: 0,
    forme: "box",
    bim: { materiau: "MDF laqué blanc", coutUHT: 380, unite: "u", norme: "DTU 36.2" },
  },
  {
    id: "porte-double",
    nom: "Porte double battant",
    categorie: "MENUISERIES",
    sousCategorie: "Portes intérieures",
    emoji: "🚪",
    dim: [1.6, 2.1, 0.08],
    couleur: "#DEB887",
    roughness: 0.6,
    metalness: 0,
    forme: "box",
    bim: { materiau: "MDF laqué blanc", coutUHT: 680, unite: "u", norme: "DTU 36.2" },
  },
  {
    id: "fenetre-simple",
    nom: "Fenêtre PVC 120x120",
    categorie: "MENUISERIES",
    sousCategorie: "Fenêtres",
    emoji: "🪟",
    dim: [1.2, 1.2, 0.1],
    couleur: "#BAE6FD",
    roughness: 0.05,
    metalness: 0,
    forme: "box",
    bim: { materiau: "PVC blanc double vitrage", fabricant: "Rehau", coutUHT: 450, unite: "u", norme: "Rw ≥32dB" },
  },
  {
    id: "baie-vitree",
    nom: "Baie vitrée coulissante 2.4m",
    categorie: "MENUISERIES",
    sousCategorie: "Fenêtres",
    emoji: "🪟",
    dim: [2.4, 2.2, 0.1],
    couleur: "#BAE6FD",
    roughness: 0.03,
    metalness: 0.2,
    forme: "box",
    bim: { materiau: "Aluminium double vitrage 4/16/4", fabricant: "Technal", coutUHT: 1800, unite: "u", norme: "Uw≤1.3" },
  },
  {
    id: "velux",
    nom: "Fenêtre de toit Velux 78x98",
    categorie: "MENUISERIES",
    sousCategorie: "Fenêtres de toit",
    emoji: "🪟",
    dim: [0.78, 0.06, 0.98],
    couleur: "#BAE6FD",
    roughness: 0.05,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "Bois/Alu double vitrage", fabricant: "VELUX", reference: "GGL 3060", coutUHT: 950, unite: "u" },
  },
  {
    id: "porte-entree",
    nom: "Porte d'entrée acier 90cm",
    categorie: "MENUISERIES",
    sousCategorie: "Portes extérieures",
    emoji: "🚪",
    dim: [0.9, 2.15, 0.07],
    couleur: "#1E3A5F",
    roughness: 0.3,
    metalness: 0.6,
    forme: "box",
    bim: { materiau: "Acier galvanisé isolé", coutUHT: 1200, unite: "u", norme: "RC2" },
  },
  {
    id: "escalier-droit",
    nom: "Escalier droit bois",
    categorie: "MENUISERIES",
    sousCategorie: "Escaliers",
    emoji: "🪜",
    dim: [0.9, 2.7, 3.6],
    couleur: "#92400E",
    roughness: 0.7,
    metalness: 0,
    forme: "escalier",
    bim: { materiau: "Chêne massif", coutUHT: 3500, unite: "u", norme: "DTU 36.3" },
  },
];

// ---------------------------------------------------------------------------
// CUISINE
// ---------------------------------------------------------------------------

const CUISINE: Element3DDef[] = [
  {
    id: "meuble-bas-cuisine",
    nom: "Meuble bas cuisine 60cm",
    categorie: "CUISINE",
    sousCategorie: "Meubles bas",
    emoji: "🍳",
    dim: [0.6, 0.87, 0.6],
    couleur: "#F8FAFC",
    roughness: 0.4,
    metalness: 0.05,
    forme: "box",
    bim: { materiau: "MDF laqué mat", fabricant: "Ikea / Schmidt", coutUHT: 280, unite: "u" },
  },
  {
    id: "meuble-haut-cuisine",
    nom: "Meuble haut cuisine 60cm",
    categorie: "CUISINE",
    sousCategorie: "Meubles hauts",
    emoji: "🗄️",
    dim: [0.6, 0.72, 0.35],
    couleur: "#F8FAFC",
    roughness: 0.4,
    metalness: 0.05,
    forme: "box",
    bim: { materiau: "MDF laqué mat", fabricant: "Ikea / Schmidt", coutUHT: 220, unite: "u" },
  },
  {
    id: "plan-travail",
    nom: "Plan de travail granit 3m",
    categorie: "CUISINE",
    sousCategorie: "Plans de travail",
    emoji: "⬛",
    dim: [3, 0.04, 0.65],
    couleur: "#374151",
    roughness: 0.1,
    metalness: 0.05,
    forme: "box",
    bim: { materiau: "Granit noir Zimbabwe", coutUHT: 420, unite: "ml", norme: "NF EN 1469" },
  },
  {
    id: "ilot-central",
    nom: "Îlot central cuisine",
    categorie: "CUISINE",
    sousCategorie: "Îlots",
    emoji: "🍽️",
    dim: [1.4, 0.92, 0.9],
    couleur: "#1E293B",
    roughness: 0.5,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "Bois/Inox", coutUHT: 2800, unite: "u" },
  },
  {
    id: "evier-cuisine",
    nom: "Évier inox 2 bacs",
    categorie: "CUISINE",
    sousCategorie: "Équipements",
    emoji: "🚰",
    dim: [0.8, 0.2, 0.5],
    couleur: "#CBD5E1",
    roughness: 0.15,
    metalness: 0.85,
    forme: "box",
    bim: { materiau: "Inox 18/10", fabricant: "Blanco", coutUHT: 380, unite: "u" },
  },
  {
    id: "hotte-cuisine",
    nom: "Hotte décorative 90cm",
    categorie: "CUISINE",
    sousCategorie: "Équipements",
    emoji: "🌬️",
    dim: [0.9, 0.5, 0.5],
    couleur: "#94A3B8",
    roughness: 0.2,
    metalness: 0.75,
    forme: "box",
    bim: { materiau: "Inox brossé", fabricant: "Elica / Faber", coutUHT: 650, unite: "u" },
  },
  {
    id: "refrigerateur",
    nom: "Réfrigérateur américain",
    categorie: "CUISINE",
    sousCategorie: "Électroménager",
    emoji: "🧊",
    dim: [0.9, 1.77, 0.7],
    couleur: "#CBD5E1",
    roughness: 0.2,
    metalness: 0.6,
    forme: "box",
    bim: { materiau: "Inox", fabricant: "Samsung / LG", coutUHT: 1400, unite: "u", norme: "A+++" },
  },
  {
    id: "four-encastrable",
    nom: "Four encastrable 60cm",
    categorie: "CUISINE",
    sousCategorie: "Électroménager",
    emoji: "🔥",
    dim: [0.6, 0.6, 0.56],
    couleur: "#1E293B",
    roughness: 0.25,
    metalness: 0.5,
    forme: "box",
    bim: { materiau: "Inox/Verre", fabricant: "Bosch / Siemens", coutUHT: 750, unite: "u", norme: "A+" },
  },
  {
    id: "lave-vaisselle",
    nom: "Lave-vaisselle 60cm",
    categorie: "CUISINE",
    sousCategorie: "Électroménager",
    emoji: "🧽",
    dim: [0.6, 0.85, 0.6],
    couleur: "#F8FAFC",
    roughness: 0.4,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "Acier émaillé", fabricant: "Bosch", coutUHT: 580, unite: "u", norme: "A+++" },
  },
];

// ---------------------------------------------------------------------------
// SANITAIRE / SALLE DE BAIN
// ---------------------------------------------------------------------------

const SANITAIRE: Element3DDef[] = [
  {
    id: "baignoire",
    nom: "Baignoire acrylique 170cm",
    categorie: "SANITAIRE",
    sousCategorie: "Bains",
    emoji: "🛁",
    dim: [1.7, 0.6, 0.75],
    couleur: "#F0F9FF",
    roughness: 0.1,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Acrylique renforcé", fabricant: "Jacob Delafon", coutUHT: 680, unite: "u", norme: "NF EN 198" },
  },
  {
    id: "douche-italienne",
    nom: "Douche à l'italienne 90x90",
    categorie: "SANITAIRE",
    sousCategorie: "Douches",
    emoji: "🚿",
    dim: [0.9, 0.02, 0.9],
    couleur: "#E0F2FE",
    roughness: 0.05,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "Receveur résine de synthèse", fabricant: "Kinedo", coutUHT: 450, unite: "u" },
  },
  {
    id: "lavabo-suspendu",
    nom: "Lavabo suspendu 60cm",
    categorie: "SANITAIRE",
    sousCategorie: "Lavabos",
    emoji: "🫧",
    dim: [0.6, 0.14, 0.48],
    couleur: "#F0F9FF",
    roughness: 0.15,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Céramique sanitaire blanche", fabricant: "Duravit", coutUHT: 280, unite: "u" },
  },
  {
    id: "meuble-vasque",
    nom: "Meuble vasque 80cm",
    categorie: "SANITAIRE",
    sousCategorie: "Meubles SDB",
    emoji: "🚿",
    dim: [0.8, 0.85, 0.48],
    couleur: "#F8FAFC",
    roughness: 0.4,
    metalness: 0.05,
    forme: "box",
    bim: { materiau: "MDF laqué + plan vasque céramique", coutUHT: 650, unite: "u" },
  },
  {
    id: "wc-suspendu",
    nom: "WC suspendu",
    categorie: "SANITAIRE",
    sousCategorie: "WC",
    emoji: "🚽",
    dim: [0.37, 0.4, 0.57],
    couleur: "#F0F9FF",
    roughness: 0.15,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Céramique sanitaire", fabricant: "Geberit / Grohe", coutUHT: 890, unite: "u" },
  },
  {
    id: "seche-serviettes",
    nom: "Radiateur sèche-serviettes",
    categorie: "SANITAIRE",
    sousCategorie: "Chauffage SDB",
    emoji: "🌡️",
    dim: [0.6, 1.1, 0.06],
    couleur: "#CBD5E1",
    roughness: 0.2,
    metalness: 0.8,
    forme: "box",
    bim: { materiau: "Acier inox", fabricant: "Zehnder", coutUHT: 480, unite: "u" },
  },
  {
    id: "colonne-douche",
    nom: "Colonne de douche hydromassante",
    categorie: "SANITAIRE",
    sousCategorie: "Douches",
    emoji: "🚿",
    dim: [0.4, 2.1, 0.1],
    couleur: "#CBD5E1",
    roughness: 0.15,
    metalness: 0.85,
    forme: "box",
    bim: { materiau: "Inox brossé", fabricant: "Grohe", coutUHT: 1200, unite: "u" },
  },
];

// ---------------------------------------------------------------------------
// SÉJOUR / SALON
// ---------------------------------------------------------------------------

const SEJOUR: Element3DDef[] = [
  {
    id: "canape-3places",
    nom: "Canapé 3 places",
    categorie: "SEJOUR",
    sousCategorie: "Assises",
    emoji: "🛋️",
    dim: [2.2, 0.85, 0.95],
    couleur: "#6B7280",
    roughness: 0.9,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Tissu résistant ou cuir", coutUHT: 1800, unite: "u" },
  },
  {
    id: "fauteuil",
    nom: "Fauteuil design",
    categorie: "SEJOUR",
    sousCategorie: "Assises",
    emoji: "🪑",
    dim: [0.85, 0.85, 0.85],
    couleur: "#78716C",
    roughness: 0.85,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Tissu / pieds métal", coutUHT: 650, unite: "u" },
  },
  {
    id: "table-basse",
    nom: "Table basse bois",
    categorie: "SEJOUR",
    sousCategorie: "Tables",
    emoji: "🪵",
    dim: [1.2, 0.42, 0.6],
    couleur: "#92400E",
    roughness: 0.6,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Chêne massif", coutUHT: 580, unite: "u" },
  },
  {
    id: "table-manger",
    nom: "Table à manger 6 couverts",
    categorie: "SEJOUR",
    sousCategorie: "Tables",
    emoji: "🍽️",
    dim: [1.8, 0.76, 0.9],
    couleur: "#7C3AED",
    roughness: 0.5,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "Verre trempé / Noyer", coutUHT: 1200, unite: "u" },
  },
  {
    id: "chaise-salle-a-manger",
    nom: "Chaise salle à manger",
    categorie: "SEJOUR",
    sousCategorie: "Assises",
    emoji: "🪑",
    dim: [0.45, 0.9, 0.5],
    couleur: "#374151",
    roughness: 0.7,
    metalness: 0.2,
    forme: "box",
    bim: { materiau: "Métal / assise tissu", coutUHT: 180, unite: "u" },
  },
  {
    id: "meuble-tv",
    nom: "Meuble TV bas 200cm",
    categorie: "SEJOUR",
    sousCategorie: "Rangements",
    emoji: "📺",
    dim: [2.0, 0.45, 0.42],
    couleur: "#1E293B",
    roughness: 0.5,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "MDF laqué noir mat", coutUHT: 750, unite: "u" },
  },
  {
    id: "bibliotheque",
    nom: "Bibliothèque murale 200cm",
    categorie: "SEJOUR",
    sousCategorie: "Rangements",
    emoji: "📚",
    dim: [2.0, 2.2, 0.35],
    couleur: "#F5F5F0",
    roughness: 0.6,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Bois MDF laqué blanc", fabricant: "Ikea Billy", coutUHT: 420, unite: "u" },
  },
];

// ---------------------------------------------------------------------------
// CHAMBRE
// ---------------------------------------------------------------------------

const CHAMBRE: Element3DDef[] = [
  {
    id: "lit-140",
    nom: "Lit 140x190cm",
    categorie: "CHAMBRE",
    sousCategorie: "Lits",
    emoji: "🛏️",
    dim: [1.4, 0.55, 2.0],
    couleur: "#E5E7EB",
    roughness: 0.8,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Tissu capitonné + lattes bois", coutUHT: 850, unite: "u" },
  },
  {
    id: "lit-160",
    nom: "Lit 160x200cm",
    categorie: "CHAMBRE",
    sousCategorie: "Lits",
    emoji: "🛏️",
    dim: [1.6, 0.55, 2.1],
    couleur: "#E5E7EB",
    roughness: 0.8,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Tissu capitonné + sommier à lattes", coutUHT: 1100, unite: "u" },
  },
  {
    id: "armoire-penderie",
    nom: "Armoire penderie 3 portes",
    categorie: "CHAMBRE",
    sousCategorie: "Rangements",
    emoji: "🚪",
    dim: [1.5, 2.2, 0.6],
    couleur: "#F8FAFC",
    roughness: 0.5,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "MDF laqué blanc / portes miroir", coutUHT: 1200, unite: "u" },
  },
  {
    id: "table-nuit",
    nom: "Table de nuit",
    categorie: "CHAMBRE",
    sousCategorie: "Tables",
    emoji: "🛏️",
    dim: [0.5, 0.55, 0.4],
    couleur: "#F5F5F0",
    roughness: 0.7,
    metalness: 0,
    forme: "box",
    bim: { materiau: "MDF laqué / chêne", coutUHT: 250, unite: "u" },
  },
  {
    id: "bureau",
    nom: "Bureau avec retour",
    categorie: "CHAMBRE",
    sousCategorie: "Bureau",
    emoji: "🖥️",
    dim: [1.6, 0.75, 0.8],
    couleur: "#F5F5F0",
    roughness: 0.6,
    metalness: 0,
    forme: "box",
    bim: { materiau: "MDF / Chêne massif", coutUHT: 680, unite: "u" },
  },
  {
    id: "commode",
    nom: "Commode 6 tiroirs",
    categorie: "CHAMBRE",
    sousCategorie: "Rangements",
    emoji: "🪵",
    dim: [0.8, 1.0, 0.45],
    couleur: "#D4A574",
    roughness: 0.65,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Bois massif / MDF", coutUHT: 580, unite: "u" },
  },
];

// ---------------------------------------------------------------------------
// SOLS & REVÊTEMENTS
// ---------------------------------------------------------------------------

const SOLS: Element3DDef[] = [
  {
    id: "carrelage-60",
    nom: "Carrelage grès 60x60cm",
    categorie: "SOLS",
    sousCategorie: "Carrelage",
    emoji: "⬜",
    dim: [5, 0.01, 5],
    couleur: "#F1F5F9",
    roughness: 0.3,
    metalness: 0.1,
    forme: "box",
    bim: { materiau: "Grès cérame rectifié", fabricant: "Emil / Marazzi", coutUHT: 45, unite: "m²", norme: "UPEC U4P3E2C2" },
  },
  {
    id: "parquet-chene",
    nom: "Parquet chêne contrecollé",
    categorie: "SOLS",
    sousCategorie: "Parquet",
    emoji: "🪵",
    dim: [5, 0.015, 5],
    couleur: "#A0522D",
    roughness: 0.6,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Chêne contrecollé huilé", fabricant: "Barlinek", coutUHT: 55, unite: "m²", norme: "A18" },
  },
  {
    id: "beton-cire",
    nom: "Béton ciré",
    categorie: "SOLS",
    sousCategorie: "Béton",
    emoji: "⬛",
    dim: [5, 0.008, 5],
    couleur: "#78716C",
    roughness: 0.4,
    metalness: 0.05,
    forme: "box",
    bim: { materiau: "Béton ciré résine époxy", coutUHT: 85, unite: "m²" },
  },
  {
    id: "moquette",
    nom: "Moquette mohair",
    categorie: "SOLS",
    sousCategorie: "Revêtements souples",
    emoji: "🟫",
    dim: [5, 0.01, 5],
    couleur: "#C8A882",
    roughness: 1.0,
    metalness: 0,
    forme: "box",
    bim: { materiau: "Mohair 100% laine", coutUHT: 65, unite: "m²" },
  },
];

// ---------------------------------------------------------------------------
// ÉQUIPEMENTS TECHNIQUES
// ---------------------------------------------------------------------------

const EQUIPEMENTS: Element3DDef[] = [
  {
    id: "radiateur-fonte",
    nom: "Radiateur fonte déco",
    categorie: "EQUIPEMENTS",
    sousCategorie: "Chauffage",
    emoji: "🌡️",
    dim: [1.0, 0.7, 0.14],
    couleur: "#F1F5F9",
    roughness: 0.5,
    metalness: 0.2,
    forme: "box",
    bim: { materiau: "Fonte de fer", fabricant: "Jaga / Zehnder", coutUHT: 680, unite: "u" },
  },
  {
    id: "climatiseur-mural",
    nom: "Climatiseur mural",
    categorie: "EQUIPEMENTS",
    sousCategorie: "CVC",
    emoji: "❄️",
    dim: [0.9, 0.3, 0.2],
    couleur: "#F8FAFC",
    roughness: 0.4,
    metalness: 0.2,
    forme: "box",
    bim: { materiau: "Plastique ABS / Aluminium", fabricant: "Daikin / Mitsubishi", coutUHT: 1200, unite: "u", norme: "A++" },
  },
  {
    id: "ballon-eau-chaude",
    nom: "Ballon eau chaude 200L",
    categorie: "EQUIPEMENTS",
    sousCategorie: "Plomberie",
    emoji: "💧",
    dim: [0.6, 1.6, 0.6],
    couleur: "#CBD5E1",
    roughness: 0.3,
    metalness: 0.7,
    forme: "cylinder",
    bim: { materiau: "Acier émaillé / inox", fabricant: "Atlantic", coutUHT: 750, unite: "u", norme: "A+" },
  },
  {
    id: "chaudiere-gaz",
    nom: "Chaudière gaz condensation",
    categorie: "EQUIPEMENTS",
    sousCategorie: "Chauffage",
    emoji: "🔥",
    dim: [0.6, 0.85, 0.35],
    couleur: "#F8FAFC",
    roughness: 0.5,
    metalness: 0.3,
    forme: "box",
    bim: { materiau: "Acier inox", fabricant: "Viessmann / Bosch", coutUHT: 2800, unite: "u", norme: "Erp A" },
  },
];

// ---------------------------------------------------------------------------
// AGENCEMENT PROFESSIONNEL
// ---------------------------------------------------------------------------

const AGENCEMENT: Element3DDef[] = [
  {
    id: "comptoir-accueil",
    nom: "Comptoir d'accueil 200cm",
    categorie: "AGENCEMENT",
    sousCategorie: "Mobilier professionnel",
    emoji: "🏢",
    dim: [2.0, 1.1, 0.6],
    couleur: "#1E293B",
    roughness: 0.3,
    metalness: 0.3,
    forme: "box",
    bim: { materiau: "MDF laqué + inox", coutUHT: 3500, unite: "u" },
  },
  {
    id: "etagere-industrielle",
    nom: "Étagère industrielle métallique",
    categorie: "AGENCEMENT",
    sousCategorie: "Rangements",
    emoji: "🗄️",
    dim: [1.5, 2.0, 0.4],
    couleur: "#374151",
    roughness: 0.5,
    metalness: 0.7,
    forme: "box",
    bim: { materiau: "Acier galvanisé", coutUHT: 380, unite: "u" },
  },
  {
    id: "cloison-amovible",
    nom: "Cloison amovible vitrée",
    categorie: "AGENCEMENT",
    sousCategorie: "Cloisonnement",
    emoji: "🪟",
    dim: [2.4, 2.5, 0.1],
    couleur: "#BAE6FD",
    roughness: 0.05,
    metalness: 0.3,
    forme: "box",
    bim: { materiau: "Verre feuilleté + profilés alu", coutUHT: 450, unite: "m²" },
  },
];

// ---------------------------------------------------------------------------
// EXPORT — bibliothèque complète
// ---------------------------------------------------------------------------

export const TOUS_ELEMENTS_3D: Element3DDef[] = [
  ...STRUCTURE,
  ...IPN,
  ...CHARPENTE,
  ...MENUISERIES,
  ...CUISINE,
  ...SANITAIRE,
  ...SEJOUR,
  ...CHAMBRE,
  ...SOLS,
  ...EQUIPEMENTS,
  ...AGENCEMENT,
];

export const CATEGORIES_3D: Record<string, { label: string; emoji: string; couleur: string }> = {
  STRUCTURE:           { label: "Structure & Maçonnerie", emoji: "🧱", couleur: "#6B7280" },
  CHARPENTE_METALLIQUE:{ label: "IPN & Charpente métallique", emoji: "🔩", couleur: "#374151" },
  CHARPENTE:           { label: "Charpente & Toiture", emoji: "🏠", couleur: "#A16207" },
  MENUISERIES:         { label: "Menuiseries", emoji: "🚪", couleur: "#7C3AED" },
  CUISINE:             { label: "Cuisine", emoji: "🍳", couleur: "#DC2626" },
  SANITAIRE:           { label: "Sanitaire & SDB", emoji: "🚿", couleur: "#0EA5E9" },
  SEJOUR:              { label: "Séjour & Salon", emoji: "🛋️", couleur: "#7C3AED" },
  CHAMBRE:             { label: "Chambre", emoji: "🛏️", couleur: "#EC4899" },
  SOLS:                { label: "Sols & Revêtements", emoji: "⬜", couleur: "#78716C" },
  EQUIPEMENTS:         { label: "Équipements techniques", emoji: "⚙️", couleur: "#0891B2" },
  AGENCEMENT:          { label: "Agencement professionnel", emoji: "🏢", couleur: "#1E293B" },
};

export function getElement3D(id: string): Element3DDef | undefined {
  return TOUS_ELEMENTS_3D.find((e) => e.id === id);
}
