// Rôles et permissions — CRM SDA Rénovation
// Ce fichier est importé côté serveur ET dans le middleware (proxy.ts)
// → pas d'import "server-only", pas de dépendances externes.

export const FULL_ACCESS_ROLES = [
  "DIRIGEANT",
  "ASSISTANT_DIRECTION",
  "DAF",
  "ADMIN", // rétro-compatibilité avec l'ancien rôle par défaut
] as const;

export const ALL_ROLES = [
  "DIRIGEANT",
  "ASSISTANT_DIRECTION",
  "DAF",
  // Travaux & Encadrement
  "CONDUCTEUR_TRAVAUX",
  "CONDUCTEUR_TRAVAUX_2",
  "CHEF_CHANTIER",
  "CHARGE_AFFAIRE",
  "INGENIEUR_STRUCTURE",
  // Études de prix
  "CHIFFREUR_METREUR_1",
  "CHIFFREUR_METREUR_2",
  // Commercial
  "COMMERCIAL",
  // Finance & Comptabilité
  "COMPTABLE",
  "ASSISTANTE_COMPTABLE",
  "EXPERT_COMPTABLE",
  // Administratif
  "ASSISTANTE_ADMINISTRATIVE",
  // Terrain
  "OUVRIER",
  "OUVRIER_2",
  "OUVRIER_3",
  "MAGASINIER",
  "LIVREUR",
  // Apprentis & Stagiaires
  "APPRENTI_1",
  "APPRENTI_2",
  "APPRENTI_3",
  "STAGIAIRE_1",
  "STAGIAIRE_2",
  "STAGIAIRE_3",
] as const;

export type Role = (typeof ALL_ROLES)[number];

export const ROLE_LABELS: Record<string, string> = {
  // Direction & Administration
  DIRIGEANT: "Dirigeant",
  ASSISTANT_DIRECTION: "Assistant(e) de direction",
  DAF: "Dir. Administratif et Financier",
  ASSISTANTE_ADMINISTRATIVE: "Assistante administrative",
  // Travaux & Encadrement
  CHARGE_AFFAIRE: "Chargé d'affaire",
  CONDUCTEUR_TRAVAUX: "Conducteur de travaux n°1",
  CONDUCTEUR_TRAVAUX_2: "Conducteur de travaux n°2",
  CHEF_CHANTIER: "Chef de chantier",
  INGENIEUR_STRUCTURE: "Ingénieur structure",
  // Études de prix
  CHIFFREUR_METREUR_1: "Chiffreur métreur n°1",
  CHIFFREUR_METREUR_2: "Chiffreur métreur n°2",
  // Commercial
  COMMERCIAL: "Commercial",
  // Finance & Comptabilité
  COMPTABLE: "Comptable",
  ASSISTANTE_COMPTABLE: "Assistante comptable",
  EXPERT_COMPTABLE: "Expert-Comptable (externe)",
  // Terrain
  OUVRIER: "Ouvrier n°1",
  OUVRIER_2: "Ouvrier n°2",
  OUVRIER_3: "Ouvrier n°3",
  MAGASINIER: "Magasinier",
  LIVREUR: "Livreur",
  // Apprentis
  APPRENTI_1: "Apprenti(e) n°1",
  APPRENTI_2: "Apprenti(e) n°2",
  APPRENTI_3: "Apprenti(e) n°3",
  // Stagiaires
  STAGIAIRE_1: "Stagiaire n°1",
  STAGIAIRE_2: "Stagiaire n°2",
  STAGIAIRE_3: "Stagiaire n°3",
  // Rétro-compatibilité
  ADMIN: "Administrateur",
};

export const ROLE_BADGE_TONES: Record<string, "blue" | "navy" | "orange" | "green" | "gray"> = {
  DIRIGEANT: "navy",
  ASSISTANT_DIRECTION: "blue",
  DAF: "blue",
  ADMIN: "navy",
  ASSISTANTE_ADMINISTRATIVE: "blue",
  CHARGE_AFFAIRE: "navy",
  CONDUCTEUR_TRAVAUX: "orange",
  CONDUCTEUR_TRAVAUX_2: "orange",
  CHEF_CHANTIER: "orange",
  INGENIEUR_STRUCTURE: "blue",
  CHIFFREUR_METREUR_1: "blue",
  CHIFFREUR_METREUR_2: "blue",
  COMMERCIAL: "green",
  COMPTABLE: "gray",
  ASSISTANTE_COMPTABLE: "gray",
  EXPERT_COMPTABLE: "gray",
  OUVRIER: "gray",
  OUVRIER_2: "gray",
  OUVRIER_3: "gray",
  MAGASINIER: "gray",
  LIVREUR: "gray",
  APPRENTI_1: "green",
  APPRENTI_2: "green",
  APPRENTI_3: "green",
  STAGIAIRE_1: "green",
  STAGIAIRE_2: "green",
  STAGIAIRE_3: "green",
};

// Routes accessibles aux rôles restreints (les routes /rh, /parametres,
// /utilisateurs ne sont PAS listées ici → full access uniquement)
export const ALL_PERMISSIONS = [
  "/",
  "/recherche",
  "/clients",
  "/fournisseurs",
  "/sous-traitants",
  "/chantiers",
  "/planning",
  "/planning-gantt",
  "/devis",
  "/ouvrages",
  "/main-oeuvre",
  "/temps-unitaires",
  "/interimaires",
  "/factures",
  "/etats-reserves",
  "/contrats-sous-traitance",
  "/ordres-mission",
  "/pv-reception",
  "/bons-commande",
  "/bons-livraison",
  "/taches",
  "/stock",
  "/tresorerie",
  "/analytique",
  "/notes-de-frais",
  "/documents",
  "/depenses",
  "/finances",       // couvre /finances/* (dashboard, TVA, impayés, rentabilité, RG, trésorerie 13 sem., rapport…)
  "/marge-rentabilite",
  "/previsionnel",
  "/comptabilite",   // couvre /comptabilite/* (bilan, FEC, rapprochement…)
  "/prospects",
  "/memoires-techniques",
  "/doe",
  "/ppsps",
  "/fiches-techniques",
  "/dtu",
  "/mutuelle",
  "/meteo",
  "/messagerie",
  "/securite",
  // Exploitation / Production
  "/exploitation/fiches-intervention",
  "/exploitation/rapports-hebdo",
  "/exploitation/non-conformites",
  "/exploitation/pv-reunion",
  "/exploitation/bons-travaux",
  "/exploitation/demandes-appro",
  "/exploitation/frais-chantier",
  // Qualité Chantier
  "/qualite/paq",
  "/qualite/autocontrole",
  "/qualite/daact",
  // Étude de prix
  "/etude-prix/debourses-secs",
  "/etude-prix/agrement-produits",
  "/etude-prix/cout-materiaux",
  "/etude-prix/approvisionement",
  "/etude-prix/pre-dimensionnement",
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

export const PERMISSION_LABELS: Record<string, string> = {
  "/": "Tableau de bord",
  "/recherche": "Recherche & Google",
  "/clients": "Clients",
  "/fournisseurs": "Fournisseurs",
  "/sous-traitants": "Sous-traitants",
  "/chantiers": "Chantiers",
  "/planning": "Planning",
  "/planning-gantt": "Planning Gantt",
  "/devis": "Devis",
  "/ouvrages": "Bibliothèque ouvrages",
  "/main-oeuvre": "Taux main d'œuvre",
  "/temps-unitaires": "Temps unitaires",
  "/interimaires": "Intérimaires",
  "/factures": "Factures",
  "/etats-reserves": "États des réserves",
  "/contrats-sous-traitance": "Contrats de sous-traitance",
  "/ordres-mission": "Ordres de mission",
  "/pv-reception": "PV de Réception",
  "/bons-commande": "Bons de commande",
  "/bons-livraison": "Bons de livraison",
  "/taches": "Tâches internes",
  "/stock": "Gestion de stock",
  "/tresorerie": "Trésorerie & P&L",
  "/analytique": "Analytique & Graphiques",
  "/notes-de-frais": "Notes de frais",
  "/documents": "Documents",
  "/depenses": "Dépenses",
  "/finances": "Finances (dashboard, TVA, impayés, RG, trésorerie 13 sem., rentabilité…)",
  "/marge-rentabilite": "Marge & Rentabilité chantiers",
  "/previsionnel": "Prévisionnel des flux",
  "/comptabilite": "Comptabilité (bilan, FEC, rapprochement…)",
  "/prospects": "Prospects",
  "/memoires-techniques": "Mémoires techniques",
  "/doe": "DOE",
  "/ppsps": "PPSPS",
  "/fiches-techniques": "Fiches techniques",
  "/dtu": "Bibliothèque DTU",
  "/mutuelle": "Mutuelle d'entreprise",
  "/meteo": "Journal Météo BTP",
  "/messagerie": "Messagerie interne",
  "/securite": "Sécurité — Alba-ayla IA",
  "/exploitation/fiches-intervention": "Fiches d'intervention",
  "/exploitation/rapports-hebdo": "Rapports hebdomadaires",
  "/exploitation/non-conformites": "Non-conformités qualité",
  "/exploitation/pv-reunion": "PV de réunion chantier",
  "/exploitation/bons-travaux": "Bons de travaux équipes",
  "/exploitation/demandes-appro": "Demandes d'approvisionnement",
  "/exploitation/frais-chantier": "Frais de chantier",
  "/qualite/paq": "Plans d'Assurance Qualité",
  "/qualite/autocontrole": "Fiches d'autocontrôle",
  "/qualite/daact": "DAACT",
  "/etude-prix/debourses-secs": "Déboursés secs (DS)",
  "/etude-prix/agrement-produits": "Fiches d'agrément produit",
  "/etude-prix/cout-materiaux": "Coût matériaux rendus chantier",
  "/etude-prix/approvisionement": "Approvisionnement chantier",
  "/etude-prix/pre-dimensionnement": "Pré-dimensionnement structurel",
};

// Groupes de permissions pour l'interface d'édition
export const PERMISSION_GROUPS: { label: string; routes: string[] }[] = [
  { label: "Général", routes: ["/", "/recherche", "/meteo", "/messagerie"] },
  // /securite est intentionnellement absent des groupes publics — réservé aux rôles full-access
  { label: "Annuaire", routes: ["/clients", "/fournisseurs", "/sous-traitants"] },
  { label: "Chantiers", routes: ["/chantiers", "/planning", "/planning-gantt"] },
  {
    label: "Ventes",
    routes: [
      "/devis",
      "/ouvrages",
      "/main-oeuvre",
      "/temps-unitaires",
      "/interimaires",
      "/factures",
      "/etats-reserves",
      "/contrats-sous-traitance",
      "/ordres-mission",
      "/pv-reception",
    ],
  },
  { label: "Achats", routes: ["/bons-commande", "/bons-livraison"] },
  {
    label: "Exploitation / Production",
    routes: [
      "/exploitation/fiches-intervention",
      "/exploitation/rapports-hebdo",
      "/exploitation/non-conformites",
      "/exploitation/pv-reunion",
      "/exploitation/bons-travaux",
      "/exploitation/demandes-appro",
      "/exploitation/frais-chantier",
    ],
  },
  {
    label: "Qualité Chantier",
    routes: ["/qualite/paq", "/qualite/autocontrole", "/qualite/daact"],
  },
  {
    label: "Gestion",
    routes: ["/taches", "/stock", "/notes-de-frais", "/documents", "/prospects"],
  },
  {
    label: "Finance & Comptabilité",
    routes: [
      "/depenses",
      "/tresorerie",
      "/finances",
      "/marge-rentabilite",
      "/previsionnel",
      "/analytique",
      "/comptabilite",
    ],
  },
  { label: "RH", routes: ["/mutuelle"] },
  { label: "Documents techniques", routes: ["/memoires-techniques", "/doe", "/ppsps", "/fiches-techniques", "/dtu"] },
  {
    label: "Étude de prix",
    routes: [
      "/etude-prix/debourses-secs",
      "/etude-prix/agrement-produits",
      "/etude-prix/cout-materiaux",
      "/etude-prix/approvisionement",
      "/etude-prix/pre-dimensionnement",
    ],
  },
];

// Permissions par défaut pour chaque rôle restreint
export const DEFAULT_PERMISSIONS: Record<string, string[]> = {
  CONDUCTEUR_TRAVAUX: [
    "/",
    "/clients",
    "/fournisseurs",
    "/sous-traitants",
    "/chantiers",
    "/planning",
    "/planning-gantt",
    "/pv-reception",
    "/etats-reserves",
    "/contrats-sous-traitance",
    "/ordres-mission",
    "/bons-commande",
    "/bons-livraison",
    "/notes-de-frais",
    "/documents",
    "/ouvrages",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/non-conformites",
    "/exploitation/pv-reunion",
    "/exploitation/bons-travaux",
    "/exploitation/demandes-appro",
    "/exploitation/frais-chantier",
    "/qualite/paq",
    "/qualite/autocontrole",
    "/qualite/daact",
    "/etude-prix/debourses-secs",
    "/etude-prix/agrement-produits",
    "/etude-prix/cout-materiaux",
    "/etude-prix/approvisionement",
    "/etude-prix/pre-dimensionnement",
  ],
  COMMERCIAL: ["/", "/clients", "/devis", "/ouvrages", "/prospects", "/documents"],
  COMPTABLE: [
    "/",
    "/fournisseurs",
    "/factures",
    "/bons-commande",
    "/bons-livraison",
    "/notes-de-frais",
    "/depenses",
    "/finances",
    "/tresorerie",
    "/comptabilite",
    "/marge-rentabilite",
    "/previsionnel",
    "/analytique",
  ],
  OUVRIER: [
    "/",
    "/planning",
    "/notes-de-frais",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/bons-travaux",
  ],
  EXPERT_COMPTABLE: [
    "/",
    "/comptabilite",
    "/finances",
    "/depenses",
    "/factures",
    "/tresorerie",
    "/marge-rentabilite",
    "/previsionnel",
    "/analytique",
  ],

  // ── Nouveaux profils ──────────────────────────────────────────────────────

  CONDUCTEUR_TRAVAUX_2: [
    "/",
    "/clients",
    "/fournisseurs",
    "/sous-traitants",
    "/chantiers",
    "/planning",
    "/planning-gantt",
    "/pv-reception",
    "/etats-reserves",
    "/contrats-sous-traitance",
    "/ordres-mission",
    "/bons-commande",
    "/bons-livraison",
    "/notes-de-frais",
    "/documents",
    "/ouvrages",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/non-conformites",
    "/exploitation/pv-reunion",
    "/exploitation/bons-travaux",
    "/exploitation/demandes-appro",
    "/exploitation/frais-chantier",
    "/qualite/paq",
    "/qualite/autocontrole",
    "/qualite/daact",
    "/etude-prix/debourses-secs",
  ],

  CHEF_CHANTIER: [
    "/",
    "/chantiers",
    "/planning",
    "/planning-gantt",
    "/notes-de-frais",
    "/documents",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/non-conformites",
    "/exploitation/pv-reunion",
    "/exploitation/bons-travaux",
    "/exploitation/demandes-appro",
    "/exploitation/frais-chantier",
    "/qualite/autocontrole",
    "/qualite/paq",
  ],

  CHARGE_AFFAIRE: [
    "/",
    "/clients",
    "/prospects",
    "/fournisseurs",
    "/sous-traitants",
    "/chantiers",
    "/devis",
    "/factures",
    "/planning",
    "/planning-gantt",
    "/pv-reception",
    "/etats-reserves",
    "/contrats-sous-traitance",
    "/ordres-mission",
    "/bons-commande",
    "/bons-livraison",
    "/notes-de-frais",
    "/documents",
    "/ouvrages",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/non-conformites",
    "/exploitation/pv-reunion",
    "/exploitation/bons-travaux",
    "/exploitation/demandes-appro",
    "/exploitation/frais-chantier",
    "/qualite/paq",
    "/qualite/autocontrole",
    "/qualite/daact",
    "/etude-prix/debourses-secs",
    "/etude-prix/cout-materiaux",
    "/etude-prix/pre-dimensionnement",
    "/marge-rentabilite",
  ],

  INGENIEUR_STRUCTURE: [
    "/",
    "/chantiers",
    "/documents",
    "/ouvrages",
    "/fiches-techniques",
    "/dtu",
    "/etude-prix/pre-dimensionnement",
    "/etude-prix/debourses-secs",
    "/etude-prix/cout-materiaux",
    "/etude-prix/agrement-produits",
    "/ppsps",
    "/qualite/paq",
    "/qualite/daact",
  ],

  CHIFFREUR_METREUR_1: [
    "/",
    "/clients",
    "/chantiers",
    "/devis",
    "/ouvrages",
    "/fiches-techniques",
    "/dtu",
    "/documents",
    "/etude-prix/debourses-secs",
    "/etude-prix/cout-materiaux",
    "/etude-prix/agrement-produits",
    "/etude-prix/approvisionement",
    "/etude-prix/pre-dimensionnement",
  ],

  CHIFFREUR_METREUR_2: [
    "/",
    "/clients",
    "/chantiers",
    "/devis",
    "/ouvrages",
    "/fiches-techniques",
    "/dtu",
    "/documents",
    "/etude-prix/debourses-secs",
    "/etude-prix/cout-materiaux",
    "/etude-prix/agrement-produits",
    "/etude-prix/approvisionement",
    "/etude-prix/pre-dimensionnement",
  ],

  ASSISTANTE_COMPTABLE: [
    "/",
    "/fournisseurs",
    "/factures",
    "/bons-commande",
    "/bons-livraison",
    "/notes-de-frais",
    "/depenses",
    "/finances",
    "/tresorerie",
    "/comptabilite",
  ],

  ASSISTANTE_ADMINISTRATIVE: [
    "/",
    "/clients",
    "/fournisseurs",
    "/sous-traitants",
    "/chantiers",
    "/devis",
    "/factures",
    "/bons-commande",
    "/bons-livraison",
    "/documents",
    "/messagerie",
    "/taches",
    "/notes-de-frais",
  ],

  MAGASINIER: [
    "/",
    "/stock",
    "/bons-commande",
    "/bons-livraison",
    "/fournisseurs",
    "/exploitation/demandes-appro",
    "/documents",
  ],

  LIVREUR: [
    "/",
    "/bons-livraison",
    "/ordres-mission",
    "/planning",
  ],

  OUVRIER_2: [
    "/",
    "/planning",
    "/notes-de-frais",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/bons-travaux",
  ],

  OUVRIER_3: [
    "/",
    "/planning",
    "/notes-de-frais",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/bons-travaux",
  ],

  APPRENTI_1: [
    "/",
    "/planning",
    "/chantiers",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/bons-travaux",
    "/notes-de-frais",
  ],

  APPRENTI_2: [
    "/",
    "/planning",
    "/chantiers",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/bons-travaux",
    "/notes-de-frais",
  ],

  APPRENTI_3: [
    "/",
    "/planning",
    "/chantiers",
    "/exploitation/fiches-intervention",
    "/exploitation/rapports-hebdo",
    "/exploitation/bons-travaux",
    "/notes-de-frais",
  ],

  STAGIAIRE_1: [
    "/",
    "/planning",
    "/chantiers",
    "/documents",
  ],

  STAGIAIRE_2: [
    "/",
    "/planning",
    "/chantiers",
    "/documents",
  ],

  STAGIAIRE_3: [
    "/",
    "/planning",
    "/chantiers",
    "/documents",
  ],
};

export function isFullAccessRole(role: string): boolean {
  return (FULL_ACCESS_ROLES as readonly string[]).includes(role);
}

export function getDefaultPermissions(role: string): string[] {
  if (isFullAccessRole(role)) return [];
  return DEFAULT_PERMISSIONS[role] ?? ["/"];
}

export function canAccess(role: string, permissions: string[], path: string): boolean {
  if (isFullAccessRole(role)) return true;
  return permissions.some((p) => path === p || path.startsWith(`${p}/`));
}
