import { COMPANY } from "@/lib/company";

// Reproduction fidèle des Conditions Générales de Fourniture de Produits et
// Services SDA Rénovation (CG_SDA Rénovation_V191125.pdf) — texte intégral,
// en colonnes, pour annexe systématique aux devis.

function EnTeteCGV({ page }: { page: 1 | 2 }) {
  return (
    <div className="mb-4 flex items-center justify-between border-b border-slate-200 pb-2">
      <div className="flex items-center gap-2">
        <img src="/logo.png" alt="SDA Rénovation" className="h-6 w-auto object-contain" />
      </div>
      <div className="text-center">
        <p className="text-[10px] font-bold text-slate-700">SDA RENOVATION</p>
        <p className="text-[9px] text-slate-500">Conditions Générales de Fourniture de Produits et Services_V191125</p>
      </div>
      <p className="text-[9px] text-slate-400">Page {page} sur 2</p>
    </div>
  );
}

function PiedCGV() {
  return (
    <div className="mt-4 border-t border-slate-200 pt-2 text-center">
      <p className="text-[9px] font-bold text-slate-600">SDA RENOVATION</p>
      <p className="text-[8px] text-slate-400">SAS au capital de 3000 euros</p>
      <p className="text-[8px] text-slate-400">Siège social : {COMPANY.adresse} - {COMPANY.codePostal} {COMPANY.ville}</p>
      <p className="text-[8px] text-slate-400">SIREN : {COMPANY.siren} RCS Toulouse</p>
      <p className="text-[8px] text-slate-400">Email : {COMPANY.email} / Tel: {COMPANY.telephone}</p>
    </div>
  );
}

const cls = {
  h: "text-[10px] font-bold text-[#1E2F6E] mt-2 mb-1",
  p: "text-[9px] leading-snug text-slate-700 text-justify mb-1.5",
};

export function CGVAnnexe() {
  return (
    <>
      {/* Page 1/2 des CGV */}
      <div className="mx-auto my-8 w-full max-w-[210mm] bg-white shadow-xl print:my-0 print:shadow-none print:break-before-page">
        <div className="px-12 py-8 print:px-10 print:py-6">
          <EnTeteCGV page={1} />
          <div className="[column-count:2] [column-gap:1.5rem]">
            <p className={cls.h}>1. Définitions</p>
            <p className={cls.p}><b>Client</b> ou <b>Maitre d&apos;Ouvrage</b> désigne la personne physique ou morale a qui le Prestataire fournit les Produits ou Services au titre du Contrat.</p>
            <p className={cls.p}><b>Conditions Générales</b> : désignent le présent document. Les Conditions Générales s&apos;appliquent à tous les Services et/ou Produits fournis par le Prestataire (l&apos;ensemble du marché, devis initial et éventuels avenants ultérieurs).</p>
            <p className={cls.p}><b>Conditions Particulières</b> : désignent les conditions stipulées dans le devis (le « Devis ») constituant l&apos;offre technique et commerciale (l&apos;« Offre ») définissant les Produits et/ou Services fournis par le Prestataire, ainsi que les modalités spécifiques afférentes à ces Produits et/ou Services.</p>
            <p className={cls.p}><b>Contrat</b> : désigne ensemble le Devis/l&apos;Offre, les Conditions Particulières, les Conditions Générales. Sauf stipulation contraire est également réputé avoir valeur contractuelle, tout document établi par le Prestataire et signé par les deux Parties (ex : comptes rendus validés, PV de réception signé etc). Etant néanmoins précisé que les prospectus, catalogue ou photographies de Produits/Services sont fournis par le Prestataire à titre informatif.</p>
            <p className={cls.p}><b>Devis</b> ou l&apos;<b>Offre</b> : désigne le devis / l&apos;offre technique et commerciale émis par le Prestataire.</p>
            <p className={cls.p}><b>SDA Rénovation</b> : désigne le prestataire (« Prestataire ») qui est une entreprise de travaux ayant notamment pour activité : la peinture intérieure et extérieure, plâtrerie, menuiserie intérieure / agencement /cuisine et salle de bain, revêtement de sol souples et durs, revêtement de murs, ravalements de façades, isolation thermique par l&apos;extérieure, couverture / toiture, maçonnerie et dallage…etc (« Service(s) ou « Prestation(s)») et la fourniture de matériaux liés aux travaux de bâtiment et aux activités exercées (« Produit(s)).</p>
            <p className={cls.p}><b>Site</b> : désigne le(s) site(s) / chantier où sont fournis les Produits/Services tels qu&apos;indiqués au Contrat.</p>

            <p className={cls.h}>2. Champ d&apos;application</p>
            <p className={cls.p}>2.1 Le Client reconnaît que toute fourniture de Produits et/ou Services sera exclusivement et intégralement régie par le Contrat. Nonobstant toute clause contraire, en aucun cas les conditions générales d&apos;achat du Client, quel que soit le support sur lequel elles sont mentionnées, ne pourront être opposées au Prestataire. Le Contrat prévaut donc sur toutes clauses des bons de commandes ou de tout autre document du Client.</p>
            <p className={cls.p}>2.2 La durée de validité du Devis du Prestataire est stipulée dans les Conditions Particulières et court à compter de sa date d&apos;établissement. Au-delà de cette période, le Prestataire n&apos;est plus tenu par les termes du Devis. A l&apos;égard du Prestataire, la commande est définitive à l&apos;accusé réception par le Prestataire d&apos;un exemplaire de l&apos;Offre non modifiée dûment signée par le Client et accompagnée de l&apos;acompte tel que prévu aux conditions tarifaires applicables. A l&apos;égard du Client et sauf application des dispositions spécifiques du Code de la consommation quant au délai de rétractation, la signature du Devis par le Client vaut commande ferme des Produits et/ou Services concernés.</p>
            <p className={cls.p}>2.3 Lorsque le Client est une personne physique ayant vocation à se prévaloir des dispositions du Code de la consommation, il indique au Prestataire, par écrit et avant la conclusion du marché, s&apos;il entend demander un prêt pour payer en totalité ou en partie les travaux, faute de quoi, il est réputé ne pas emprunter et perdre le bénéfice des dispositions du Code de la consommation sur le crédit immobilier et le crédit à la consommation.</p>

            <p className={cls.h}>3. Prise d&apos;effet - Durée - Résiliation</p>
            <p className={cls.p}><b>3.1 Prise d&apos;effet - Durée</b> — Le Contrat prend effet à compter de sa signature par les deux Parties. Le cas échéant la durée des Prestations fait l&apos;objet d&apos;un calendrier estimatif dans les conditions stipulées au Contrat.</p>
            <p className={cls.p}><b>3.2 Résiliation</b> — (a) En cas de manquement grave et répété par l&apos;une des Parties à l&apos;une de ses obligations substantielles prévues au Contrat auquel la Partie défaillante n&apos;aurait pas pallié dans un délai de trente (30) jours à compter de la première présentation d&apos;une lettre recommandée avec accusé de réception notifiant le manquement en cause, l&apos;autre Partie pourra notifier la résiliation du Contrat, avec effet immédiat et de plein droit, par lettre recommandée avec accusé de réception, sous réserve de tous les dommages-intérêts auxquels elle pourrait prétendre.</p>
            <p className={cls.p}>(b) Le Prestataire peut résilier de plein droit et immédiatement le Contrat en cas de : (i) Non-paiement par le Client de tout ou partie d&apos;une facture ; (ii) Modification unilatérale par le Client des conditions initiales d&apos;exécution du chantier ayant un impact notamment sur les conditions financières et techniques du Contrat. La résiliation anticipée se traduit alors par l&apos;arrêt des travaux par le Prestataire qui reprend possession de tous ses équipements.</p>
            <p className={cls.p}>(c) En cas de résiliation anticipée imputable au Client : (i) avant le démarrage des travaux, le montant des acomptes versés sera conservé par le Prestataire à titre d&apos;indemnisation, sans préjudice des frais supplémentaires qui pourraient être dus, sur justificatif, tels que le coût des matériaux et matériels commandés ou fabriqués ; (ii) après le démarrage des travaux, le Client doit immédiatement s&apos;acquitter auprès du Prestataire de toutes les sommes dont il demeure redevable au jour de la résiliation, ce, sans préjudice des frais supplémentaires qui pourraient être dus.</p>
            <p className={cls.p}>3.3 Conformément à l&apos;article 1229 du Code civil, les prestations échangées ayant trouvé leur utilité au fur et à mesure de l&apos;exécution réciproque du Contrat, en cas de résiliation il n&apos;y aura pas lieu à restitution. Par dérogation expresse à l&apos;article 1217 du Code civil, les Parties conviennent qu&apos;en cas d&apos;inexécution ou mauvaise exécution du Contrat, les seules sanctions opposables au Prestataire sont celles stipulées au Contrat. Toutes les obligations qui, par nature, perdurent au-delà du Contrat, poursuivront leurs effets après la cessation du Contrat.</p>

            <p className={cls.h}>4. Obligations des Parties – Conditions d&apos;exécution</p>
            <p className={cls.p}>4.1 Les Parties sont conscientes de ce que les Services nécessitent une collaboration active et régulière de leur part et s&apos;y engagent. A ce titre, le Client communiquera au Prestataire toutes les informations et documents utiles, complets et exacts pour lui permettre de remplir ses obligations au titre du Contrat. Chaque Partie s&apos;engage à affecter au suivi des Services des interlocuteurs, le cas échéant dotés de la qualification et de l&apos;expérience nécessaire. Chaque Partie s&apos;engage à respecter les législations et réglementations françaises et européennes en vigueur, notamment en matière d&apos;hygiène, d&apos;environnement et de sécurité du travail.</p>
            <p className={cls.p}>4.2 Le Prestataire s&apos;engage à apporter tout le soin raisonnablement possible à la fourniture des Produits et à l&apos;exécution des Services, et supporte à ce titre une obligation de moyens. Lors de la réalisation des Services sur Site du Client, le Prestataire s&apos;engage à respecter les règles d&apos;hygiène et de sécurité spécifiques au Site, lesquelles devront être préalablement transmises par le Client. En cas de danger pour les intervenants mandatés, le Prestataire pourra suspendre la fourniture des Produits et Services. Le Prestataire s&apos;engage à conseiller le Client sur les Services et les Produits fournis et en particulier le mettre en garde contre toute difficulté rencontrée dans l&apos;exécution des Services qui remettrait en cause leur poursuite. Le Prestataire s&apos;engage également à confier l&apos;exécution des Services à des personnes disposant de la qualification et de la formation requises et répondant aux exigences des Services.</p>
            <p className={cls.p}>4.3 Le Client facilite l&apos;accès à ses Sites aux intervenants mandatés par le Prestataire. Lors de la fourniture des Produits et/ou des Services, le Client s&apos;engage notamment à : (i) Mettre à la disposition du Prestataire tous les équipements et moyens indispensables à la fourniture des Produits et/ou la réalisation des Services qui sont à sa charge en application des Conditions Particulières ; (ii) effectuer avec diligence et dans les délais prévus, toutes les validations et réceptions nécessaires ; (iii) suivre toute recommandation, instruction du Prestataire liée aux Produits et/ou Services, et notamment prévoir un environnement respectant des conditions hygrométriques, climatiques et de stockage, adaptées aux Produits et s&apos;assurer que le site est propre et débarrassé de tous déblais ; (iv) obtenir toutes les autorisations, permis et licences nécessaires à l&apos;exécution du Contrat, prévenir ses voisins directs de la date de démarrage des travaux, leur laissant ainsi la possibilité de faire constater par voie d&apos;huissier l&apos;état de leur intérieur, effectuer préalablement toute déclaration ou obtenu toute autorisation rendue nécessaire notamment par les règles de voirie, d&apos;urbanisme, de copropriété, de sécurité. Il sera tenu d&apos;avoir souscrit une assurance Dommage-Ouvrage et d&apos;avoir réalisé les diagnostics avant travaux (DAT). Il informera le Prestataire des contraintes, risques et dangers dont il aura connaissance. Etant rappelé qu&apos;il incombe au Maître d&apos;ouvrage de faire son affaire de l&apos;ensemble des formalités légales et / ou autorisations administratives nécessaires à la réalisation des travaux prévus au Contrat et à défaut de tenir le Prestataire indemne de l&apos;ensemble des conséquences afférentes ; (v) permettre le libre accès au lieu d&apos;installation des Produits et de réalisation des Services pour le personnel mandaté par le Prestataire ; (vi) mettre à la disposition du Prestataire notamment l&apos;eau, l&apos;électricité, les accès, les aires de stockage et d&apos;installation nécessaires à la réalisation des travaux, en quantités suffisantes, gratuitement et à proximité du chantier (notamment et le cas échéant : des locaux décents à usage de vestiaires, réfectoire, WC). En cas d&apos;impossibilité ou d&apos;insuffisance, les installations nécessaires seront facturées au Client. Le Client autorise expressément le Prestataire à prendre en cas d&apos;urgence, toutes dispositions conservatoires nécessaires, sous réserve de l&apos;en informer.</p>
            <p className={cls.p}>4.4 Sauf stipulation expresse contraire, les délais d&apos;exécution stipulés sont estimatifs et donnés à titre purement indicatif. Le cas échéant, le délai convenu à la contractualisation correspond au périmètre connu à date, et s&apos;entend hors travaux modificatifs ultérieurs et sous réserve notamment : du respect par le Client des conditions de paiement, la fourniture en temps utiles des spécifications techniques et études, la réalisation par le Client des choix demandés, la disponibilité et l&apos;état des lieux, mise à disposition de l&apos;eau et de l&apos;électricité, l&apos;acheminement à temps des éventuels équipements fournis par le Client, respect du planning par d&apos;éventuels autres intervenants sur le chantier, absence d&apos;intempéries pour les travaux extérieurs, absence de cas de force majeure, d&apos;événements sociaux, politiques, économiques ou techniques entravant la marche des fournisseurs du Prestataire en composants, en énergie ou en matières premières. Dans les cas précités, le délai d&apos;exécution sera prolongé de plein droit. Tout délai d&apos;exécution convenu a vocation à être prolongé de plein droit en cas notamment : d&apos;intempéries rendant impossible toute exécution des travaux convenus, de force majeure, travaux supplémentaires ou imprévus, retard du fait du Client ou non-exécution par lui des obligations à sa charge au titre du Contrat. En tout état de cause, l&apos;engagement du Prestataire est lié à la réalisation par le Client des choix inhérents à son chantier (modèles d&apos;équipements, revêtements…). Le Prestataire avise régulièrement le Client des choix à réaliser et des dates maximales de ces choix. Le Client s&apos;engage à fournir les réponses au rythme demandé. En cas de modification substantielle, le Prestataire informera le Client des impacts sur le calendrier, par voie d&apos;avenants, devis complémentaires ou comptes rendus de chantier adressés par email. L&apos;acceptation par le Client de travaux supplémentaires, induit l&apos;acceptation du délai supplémentaire correspondant.</p>
            <p className={cls.p}>4.5 Lorsque les Conditions Particulières prévoient des pénalités du fait d&apos;un retard imputable directement et exclusivement au Prestataire, elles s&apos;entendent en jours ouvrés, dans la limite de 5% du montant total HT effectivement payé par le Client au titre du Contrat. Le paiement desdites pénalités par le Prestataire est libératoire. Ainsi, conformément à l&apos;article 1231-5 du Code civil, le retard ayant donné lieu à l&apos;application de pénalités n&apos;est pas susceptible d&apos;entraîner ni résiliation du Contrat, ni autre indemnité sous quelque forme que ce soit.</p>
            <p className={cls.p}>4.6 La fin des travaux est matérialisée par une réunion de réception, qui fera l&apos;objet d&apos;un procès-verbal de réception. La réception des travaux a lieu dès leur achèvement. A la demande du Prestataire, elle est prononcée par le Client, avec ou sans réserve. La réception libère le Prestataire de toutes les obligations contractuelles autres que les garanties légales. En cas de réserves, le Prestataire s&apos;engage à les lever dans le délai convenu et indiqué sur le Procès-Verbal. Dans les deux (2) jours calendaires suivant la levée des réserves, le Client doit adresser au Prestataire le constat de levée de réserves daté et signé. A défaut, la réception est tacite et réputée &laquo;&nbsp;sans réserve&nbsp;&raquo;. En cas de refus, les motifs de refus de réception doivent être indiqués sur le procès-verbal de réception ou à défaut, les motifs de refus de réception doivent être précisés par lettre recommandée avec accusé de réception dans les trois (3) jours calendaires suivants la demande du Prestataire. Dans le cas où la réception doit intervenir judiciairement, les frais correspondants seront à la charge exclusive du Client. En tout état de cause, le Client s&apos;engage à ne pas retarder la réception. Aucun aménagement, même partiel, stockage ou utilisation des Produits par le Client ne sera possible sans réunion et procès-verbal de réception, faute de quoi la réception sera tacite et réputée &laquo;&nbsp;sans réserve&nbsp;&raquo;.</p>

            <p className={cls.h}>5. Conditions financières</p>
            <p className={cls.p}>5.1 Les prix hors taxes applicables aux Produits/Services fournis sont stipulés aux Conditions Particulières. Le taux de TVA qui sera appliqué sera le taux de TVA légal en vigueur au jour de la facturation. Sauf disposition expresse contraire, les prix s&apos;entendent unitaires et hors obstacles non visibles, non signalés ou non décelables au moment de la remise de l&apos;Offre qui apparaissent au cours des travaux. Tous travaux non prévus explicitement dans l&apos;Offre seront considérés comme travaux supplémentaires. Ils donneront lieu à la signature d&apos;un avenant avant leur exécution. Les prix seront révisés mensuellement par application de la formule de révision définie aux Conditions Particulières. Si pour quelque motif que ce soit (notamment économique, législatif ou autre), l&apos;équilibre économique du Contrat venait à être rompu, le Prestataire en avertira le Client et les Parties s&apos;efforceront de rechercher toute correction à cette situation nouvelle. A défaut de solution trouvée entre les Parties sous 30 jours calendaires, le Prestataire peut dénoncer le Contrat par lettre recommandée avec accusé de réception moyennant un préavis d&apos;un mois.</p>
            <p className={cls.p}>5.2 Les paiements se font selon les conditions spécifiées au Contrat. Sauf dispositions particulières mentionnées au Devis, le Prestataire demande : (i) un acompte de 30 % du montant du marché à la commande et avant tout début d&apos;exécution des travaux ; (ii) puis le règlement de situations travaux au gré de l&apos;avancement du chantier ou pour tous travaux d&apos;une durée supérieure à trente (30) jours des acomptes mensuels au prorata de l&apos;avancement ; (iii) en fin de travaux, le solde à la réception des travaux, sauf stipulation expresse au Devis prévoyant une retenue de levée des réserves qui en tout état de cause ne peut dépasser 5% du montant du Contrat. Par défaut, aucune retenue de garantie ne s&apos;applique aux Prestations. La facturation définitive correspondra au montant du décompte définitif établi par le Prestataire prenant en compte les travaux exécutés, y compris les éventuels travaux supplémentaires.</p>
          </div>
          <PiedCGV />
        </div>
      </div>

      {/* Page 2/2 des CGV */}
      <div className="mx-auto my-8 w-full max-w-[210mm] bg-white shadow-xl print:my-0 print:shadow-none print:break-before-page">
        <div className="px-12 py-8 print:px-10 print:py-6">
          <EnTeteCGV page={2} />
          <div className="[column-count:2] [column-gap:1.5rem]">
            <p className={cls.p}>5.3 Sauf délai de règlement plus court stipulé aux Conditions Particulières, les factures seront réglées au Prestataire sous trente (30) jours à compter de la date d&apos;émission de la facture. Aucun escompte ne sera accordé pour paiement anticipé. En cas de défaut ou de retard de paiement de tout ou partie d&apos;une facture, le Client sera de plein droit redevable d&apos;une pénalité de retard égale au taux d&apos;intérêt mentionné à l&apos;article L.441-10 du Code de commerce. Il est précisé que cette pénalité est exigible le jour suivant la date de règlement figurant sur la facture. En outre, le Client sera de plein droit débiteur, à l&apos;égard du Prestataire, d&apos;une indemnité forfaitaire pour frais de recouvrement de 40 euros. Dans le cas où les frais de recouvrement exposés seraient supérieurs au montant de cette indemnité forfaitaire, le Prestataire pourra également demander une indemnisation complémentaire que le Client s&apos;engage à payer. Tout retard ou défaut de paiement autorisera le Prestataire à suspendre les Services et à résilier le Contrat en tout ou partie. Le Client n&apos;est pas autorisé à retenir, pour quelque cause que ce soit, tout ou partie des sommes dues, ni à effectuer une quelconque compensation, à quelque titre que ce soit.</p>
            <p className={cls.p}>5.4 Lorsque le montant des travaux, déduction faite de l&apos;acompte versé à la commande, est supérieur à douze mille (12000) euros, qu&apos;il ait recours à un crédit spécifique travaux ou non, le Client doit en garantir le paiement conformément aux dispositions de l&apos;article 1799-1 du Code civil.</p>
            <p className={cls.p}>5.5 Le transfert de propriété des Produits au Client sera retardé jusqu&apos;au paiement intégral du prix, des frais et accessoires. Seul sera considéré comme un paiement intégral, l&apos;encaissement effectif et définitif du prix par le Prestataire. A défaut, le Prestataire pourra reprendre, à première demande de sa part, les Produits détenus par le Client et qui n&apos;auraient pas été intégralement payés. Les Produits vendus par le Prestataire et en stock chez le Client seront irréfragablement présumés correspondre aux Produits dont le prix n&apos;aurait pas été payé. Le Client autorise d&apos;ores et déjà le Prestataire à faire dresser un inventaire et à reprendre et/ou mettre sous séquestre les Produits impayés ou réputés comme tels.</p>

            <p className={cls.h}>6. Garantie</p>
            <p className={cls.p}>6.1 Les Prestations sont effectuées conformément aux normes et usages de la profession, selon les tolérances d&apos;usage et en tenant compte des conditions d&apos;exploitation et d&apos;utilisation du Client, ainsi que des spécificités et de l&apos;environnement du Site.</p>
            <p className={cls.p}>6.2 Seules les garanties légales sont applicables aux Produits. La garantie légale des vices cachés prévue par les articles 1641 et suivants du Code civil est mise en œuvre dans le respect des dispositions applicables. Lorsque le Client a vocation à se prévaloir des dispositions du Code de la consommation, il agit en garantie légale de conformité ou en garanties des vices cachés, conformément aux dispositions des articles L 217-4 à L 271-16 du Code de la consommation. En tout état de cause, la garantie ne couvre ni l&apos;usure normale des Produits ni l&apos;adaptation de ceux-ci aux besoins ou objectifs du Client non stipulés au Contrat. En cas de fourniture de Produits, cette fourniture s&apos;effectue en l&apos;état et sans garantie commerciale d&apos;aucune sorte de la part du Prestataire qui se contente de répercuter au Client les éventuelles garanties fournies par les fabricants de ces Produits. Le cas échéant, le Prestataire informe le Client de la durée de disponibilité des pièces détachées des Produits telle que communiquée par les fournisseurs desdits Produits.</p>
            <p className={cls.p}>6.3 Tout défaut imputable au Prestataire doit être notifié sous 48 heures par le Client qui s&apos;abstiendra d&apos;intervenir directement ou de faire intervenir un tiers en lieu et place du Prestataire. Dans ce cas, la garantie est limitée à la stricte reprise des travaux initialement entrepris. L&apos;usure normale ou les défaillances du Client, d&apos;un tiers ou les cas de force majeure n&apos;entrent pas dans la garantie.</p>

            <p className={cls.h}>7. Responsabilité et Assurances</p>
            <p className={cls.p}>7.1 Le Prestataire garantit être titulaire de contrats d&apos;assurance adaptés aux risques encourus en matière de Responsabilité Civile Professionnelle et de Garantie Décennale. A sa demande, le Prestataire communiquera au Client une attestation d&apos;assurance indiquant la nature, le montant et la durée de la garantie.</p>
            <p className={cls.p}>7.2 Le Prestataire s&apos;engage à apporter tout le soin raisonnablement possible à la fourniture des Produits et à l&apos;exécution des Services. Eu égard à la nature des Prestations, les Parties conviennent que le Prestataire supporte une obligation de moyens. Sa responsabilité ne peut être engagée qu&apos;en réparation d&apos;un préjudice direct, réel, personnel et certain subi par le Client pour autant que le Client rapporte la preuve que la faute du Prestataire (ou d&apos;un tiers mandaté par le Prestataire pour l&apos;exécution des Prestations) est la cause de ce préjudice, à l&apos;exclusion des préjudices indirects, pertes d&apos;exploitation, de productivité, atteintes à l&apos;image de marque, ou pertes liées à des engagements à l&apos;égard de tiers. Sauf hypothèse où la responsabilité du Prestataire ne peut être limitée ou exclue conformément au droit applicable, en cas de responsabilité du Prestataire envers le Client, pour toute la durée du Contrat et pour l&apos;ensemble des causes et sinistres, du fait de l&apos;exécution ou de la non-exécution par le Prestataire de ses obligations, celui-ci sera responsable des dommages directs subis par le Client dans la limite, d&apos;un montant équivalent au prix HT payé au titre du Contrat par le Client. Ce montant inclut les indemnités forfaitaires et/ou pénalités prévues au titre du Contrat. Le Prestataire ne prend d&apos;engagement que vis-à-vis du Client. En conséquence, en cas d&apos;action de tiers tels que les clients du Client à l&apos;encontre du Prestataire, le Client en devra garantie à ce dernier.</p>

            <p className={cls.h}>8. Propriété intellectuelle, confidentialité et non concurrence</p>
            <p className={cls.p}>8.1 Les documents transmis par le Prestataire (notamment les études, devis, plans et documents de toute nature remis ou envoyés par le Prestataire), de quelque nature qu&apos;ils soient, relèvent de son savoir-faire et de sa propriété intellectuelle. Ils sont confidentiels et transmis aux seuls interlocuteurs désignés par le Client dans le cadre de leur action au titre du Contrat. Le Client ou son interlocuteur ne peuvent en faire un usage externe ou les transmettre à des tiers ou concurrents du Prestataire, ni les reproduire, sans son accord écrit. Ils restent sa propriété et doivent être rendus au terme du Contrat ou à sa demande.</p>
            <p className={cls.p}>8.2 Le Prestataire pourra faire usage à des fins commerciales des photos des Prestations réalisées, le Client lui accordant libre droit à l&apos;image. Le Prestataire préservera l&apos;anonymat du Client en ne mentionnant ni son nom ni l&apos;adresse précise du chantier sauf accord de ce dernier. Le Client peut s&apos;opposer à l&apos;utilisation des images par demande expresse avant la réception des travaux.</p>

            <p className={cls.h}>9. Données Personnelles</p>
            <p className={cls.p}>9.1 Les Parties s&apos;engagent à respecter l&apos;ensemble des lois et réglementations qui leur sont applicables en matière de traitement des données, ce qui inclut la loi du 6 janvier 1978 modifiée relative aux informations nominatives, les réglementations ou textes y afférent ainsi que le Règlement européen 2016/679 entré en vigueur du 25 mai 2018.</p>
            <p className={cls.p}>9.2 Au titre de l&apos;exécution du Contrat, le Prestataire collecte les données personnelles du Client et/ou ses préposés. L&apos;accès à ces données est strictement limité au Prestataire, ses employés et/ou sous-traitants, habilités à les traiter en raison de leurs fonctions et pour les besoins de l&apos;exécution du Contrat ou à l&apos;accomplissement par le Prestataire de ses obligations légales et règlementaires ou encore à l&apos;exercice des prérogatives lui étant légalement reconnues. Elles ne sont conservées que le temps nécessaire à ces objectifs et sont stockées en France. Conformément aux dispositions légales et règlementaires applicables, le Client et/ou les personnes concernées bénéficient d&apos;un droit d&apos;accès, de rectification, de portabilité et d&apos;effacement de ses données ou encore de limitation du traitement. Elles peuvent également s&apos;opposer au traitement des données les concernant, sous réserve de la production d&apos;un justificatif d&apos;identité valide, en contactant le Prestataire ({COMPANY.email}).</p>

            <p className={cls.h}>10. Force majeure</p>
            <p className={cls.p}>Dans le cas où un événement de force majeure surviendrait pendant la durée du Contrat, la Partie affectée par l&apos;évènement le notifie dans les meilleurs délais à l&apos;autre Partie par écrit, et l&apos;exécution de l&apos;obligation affectée par l&apos;évènement de force majeure est alors suspendue dans un premier temps. De façon expresse, sont considérés comme cas de force majeure ou cas fortuit, (i) ceux correspondant à la définition prévue à l&apos;article 1218 du Code Civil et ceux habituellement retenus par la jurisprudence des Cours et Tribunaux français mais également (ii) les cas que les Parties conviennent d&apos;assimiler comme tels, à savoir (i) les grèves ou conflits sociaux, (ii) le blocage des moyens de transport, d&apos;approvisionnement, de communications (iii) les tremblements de terre, incendies, tempêtes, inondations, pandémies, (iv) les pannes de fourniture des fluides extérieures aux Parties, (v) les guerres et émeutes, (vi) le fait du prince ou de toute autre circonstance indépendante de la volonté des Parties empêchant l&apos;exécution normale du Contrat. Si la force majeure persiste au-delà d&apos;une période de trente (30) jours, les Parties se consulteront pour statuer sur la poursuite de tout ou partie du Contrat.</p>

            <p className={cls.h}>11. Cession et sous-traitance</p>
            <p className={cls.p}>11.1 Nulle Partie ne peut céder, apporter ou transférer, même par voie de fusion, le Contrat à un tiers, sans l&apos;accord écrit et préalable de l&apos;autre Partie.</p>
            <p className={cls.p}>11.2 Le Prestataire pourra sous-traiter tout ou partie de ses obligations et/ou faire appel aux compétences ou à l&apos;expérience particulière de certains tiers experts pour l&apos;exécution des Services.</p>

            <p className={cls.h}>12. Autres dispositions</p>
            <p className={cls.p}>12.1 Le fait pour une Partie de ne pas invoquer une stipulation quelconque du Contrat ne saurait être analysé comme une renonciation et n&apos;affecte pas le droit ultérieur de la Partie à l&apos;appliquer ou à l&apos;invoquer.</p>
            <p className={cls.p}>12.2 L&apos;invalidité ou l&apos;inopposabilité d&apos;une partie des stipulations du Contrat n&apos;affectera pas la validité ou l&apos;opposabilité des autres stipulations qui resteront pleinement en vigueur.</p>
            <p className={cls.p}>12.3 Le Contrat ne pourra être modifié valablement que par un écrit signé des représentants des deux Parties.</p>

            <p className={cls.h}>13. Droit applicable et Règlement des litiges</p>
            <p className={cls.p}>13.1 Le Contrat est soumis au droit français. En cas de différend concernant le Contrat et après recherche infructueuse d&apos;une solution amiable, compétence exclusive est attribuée au Tribunal de Commerce du siège social du Prestataire, nonobstant pluralité de défendeurs ou appel en garantie et également en cas de procédure d&apos;urgence ou conservatoire, en référé ou par requête.</p>
            <p className={cls.p}>13.2 Le Client, personne physique ayant vocation à se prévaloir des dispositions du Code de la consommation, peut, après échec d&apos;une procédure amiable initiée auprès du Prestataire, recourir à la médiation de la consommation conformément aux articles L661-1 et s du Code de la consommation.</p>
          </div>
          <PiedCGV />
        </div>
      </div>
    </>
  );
}
